import { useEffect, useState } from "react";
import { Header } from "./components/Header";
import { StatStrip } from "./components/StatStrip";
import { MapPanel } from "./components/MapPanel";
import { TrackList } from "./components/TrackList";
import { EventLog } from "./components/EventLog";
import { SensorChannels } from "./components/SensorChannels";
import { EvidencePanel } from "./components/EvidencePanel";
import { useLiveFeed } from "./hooks/useLiveFeed";

export default function App() {
  const { frame, events, connection } = useLiveFeed();
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const sensor = frame?.sensor;
  const tracks = frame?.tracks ?? [];
  const selected = tracks.find((track) => track.track_id === selectedId) ?? null;

  // Drop the selection when that track leaves coverage, so the highlight
  // never points at something that isn't there any more.
  useEffect(() => {
    if (selectedId && !tracks.some((track) => track.track_id === selectedId)) {
      setSelectedId(null);
    }
  }, [tracks, selectedId]);

  return (
    <div className="flex min-h-full flex-col">
      <Header
        sensor={sensor}
        connection={connection}
        modelReady={frame?.model_ready ?? false}
      />

      <main className="mx-auto w-full max-w-[1600px] flex-1 px-4 py-4 sm:px-6">
        <StatStrip stats={frame?.stats} />

        <div className="mt-4 grid gap-4 lg:grid-cols-3 lg:items-stretch">
          <div className="panel h-[420px] overflow-hidden lg:col-span-2 lg:h-[640px]">
            {sensor ? (
              <MapPanel
                sensor={sensor}
                tracks={tracks}
                selectedId={selectedId}
                onSelect={setSelectedId}
              />
            ) : (
              <div className="flex h-full items-center justify-center px-6 text-center">
                <p className="text-sm text-muted">
                  {connection === "offline"
                    ? "No feed. Check that the backend is running on port 8000, then this will reconnect on its own."
                    : "Waiting for the first frame from the sensor feed."}
                </p>
              </div>
            )}
          </div>

          <div className="grid gap-4 lg:h-[640px] lg:grid-rows-2">
            {sensor && (
              <TrackList
                tracks={tracks}
                sensor={sensor}
                selectedId={selectedId}
                onSelect={setSelectedId}
              />
            )}
            <EventLog events={events} onSelect={setSelectedId} />
          </div>
        </div>

        {sensor && <SensorChannels track={selected} sensor={sensor} />}

        <EvidencePanel track={selected} />

        <p className="mt-4 text-[11px] leading-relaxed text-muted/70">
          Every track on this screen is generated by the software simulator in{" "}
          <code className="readout text-muted">backend/app/simulator.py</code>. No radar, RF
          receiver, or other sensor hardware is connected. Built for monitoring practice and
          learning.
        </p>
      </main>
    </div>
  );
}
